### PR TITLE
Issue 17 - Handling moving Spy onto Room & Ninja

### LINKED ISSUE #17: When a Spy makes an Illegal move, do they get another chance to move?
If a Spy walked onto the wrong side of a room or tried to walk out of bounds does he get another chance?

### PR DESCRIPTION
**Pull request by jtara1**
Updated some of the `stepOn(...)` methods.

`UI.playerTurn()` now prints grid then calls itself if `ILLEGAL` move was attempted.

This fixes https://github.com/Jester565/SpyNinjaGame/issues/17

### CODE REVIEW

File: SpyGame/src/edu/cpp/cs/cs141/final_proj/MoveStatus.java [hunk 1]
```diff
@@ -9,7 +9,7 @@
 	 * Describes the result of the attempted movement.
 	 */
 	public enum MOVE_RESULT {
-		ILLEGAL, LEGAL, UNMOVED, WIN, LOSE, POWERUP
+		ILLEGAL, LEGAL, UNMOVED, WIN, LOSE, POWERUP;
```
Comment (Jester565) [inline SpyGame/src/edu/cpp/cs/cs141/final_proj/MoveStatus.java:12]: Out of curiosity... Is there a point to the semicolon?

File: SpyGame/src/edu/cpp/cs/cs141/final_proj/UserInterface.java [hunk 2]
```diff
@@ -184,14 +184,14 @@ else if (USER_COMMAND.abbreviatedKeyCodes().containsKey(userInput)) {
...
-					System.out.println(game.displayBoard());
-					moveDir = getUserDirection("move");
+
+			moveStatus = game.playerMove(moveDir);
+			System.out.println("Move Status: " + moveStatus.msg);
+			
+			// ILLEGAL move attempted, print grid & call this method again
+			if (moveStatus.moveResult == MOVE_RESULT.ILLEGAL) {
+				System.out.println(game.displayBoard());
+				playerTurn();
```
Comment (Jester565) [inline SpyGame/src/edu/cpp/cs/cs141/final_proj/UserInterface.java:194]: That was pretty sneaky.  Could you put in a comment making it more obvious like //RECURSION

File: SpyGame/src/edu/cpp/cs/cs141/final_proj/MoveStatus.java (hunk 1 above)
Comment (jtara1) [reply SpyGame/src/edu/cpp/cs/cs141/final_proj/MoveStatus.java:12]: I thought it was part of the syntax, but it seems to work the same way with or without the semicolon so I guess there is no point to it. I'd just add it in for consistency since most lines of code end with a semicolon, but idk if this is part of some style standards or not.

**Comment by Jester565** [comment]
Yeah, its naming so it probably doesn't matter but if you look here
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html , they seem
to use it whenever there's like a constructor.  Not saying you have to do
it, just interesting.
